const products = [
    {
        id: 1,
        name: "Eclipse Noir Black Table",
        imageUrl: "/Product_img/products1.png",
        rating: 4.5,
        price: 29.99,
        reviews: 245,
        type: "Table",
        brand: "VisiFurnish",
        material: "Wood",
        color: "Black",
        weight: "Light",
        stock: 10,
        shortDescription: "Elegant black wooden table for modern homes.",
        detailDescription: "The Eclipse Noir Table is crafted with premium wood and finished in sleek black, adding sophistication to any living space. Lightweight yet sturdy, it's perfect for both functional use and aesthetic appeal. Ideal for dining or living rooms."
       
    },
    {
        id: 2,
        name: "Rustic Harmony Coffee Table",
        imageUrl: "/Product_img/products2.png",
        rating: 4.2,
        price: 39.99,
        reviews: 130,
        type: "Table",
        brand: "VisiNest",
        material: "Wood",
        color: "Brown",
        weight: "Medium",
        stock: 8,
        shortDescription: "Stylish brown coffee table with a minimalist design.",
        detailDescription: "The Rustic Harmony Coffee Table features a minimalist wooden design, perfect for any contemporary living room. Its medium-weight build ensures durability while maintaining easy mobility. Ideal for serving beverages or as a stylish centerpiece."
    },
    {
        id: 3,
        name: "Majestic Leather Lounger",
        imageUrl: "/Product_img/products3.png",
        rating: 5.0,
        price: 49.99,
        reviews: 310,
        type: "Sofa",
        brand: "VisiARrange",
        material: "Leather",
        color:"Brown",
        weight: "Heavy",
        stock: 5,
        shortDescription: "Luxurious leather sofa with a timeless design.",
        detailDescription: "The Majestic Leather Lounger offers premium comfort with its high-quality leather upholstery. The elegant gray finish pairs well with modern and traditional interiors alike. Perfect for living rooms, offering a blend of style and comfort."

    },
    {
        id: 4,
        name: "Velvet Bliss Recliner Sofa",
        imageUrl: "/Product_img/products4.png",
        rating: 5.0,
        price: 49.99,
        reviews: 310,
        type: "Sofa",
        brand: "VisiFurnish",
        material: "Fabric",
        color: "Brown",
        weight: "Medium",
        stock: 7,
        shortDescription: "Comfortable fabric recliner sofa in a sleek black finish.",
        detailDescription: "Relax in style with the Velvet Bliss Recliner, designed for maximum comfort. The soft fabric and reclining feature make it perfect for unwinding after a long day. With its modern black finish, it easily complements any room decor."
    },
    {
        id: 5,
        name: "Cozy Nook Single Seat Sofa",
        imageUrl: "/Product_img/products5.png",
        rating: 4.0,
        price: 19.99,
        reviews: 120,
        type: "Sofa",
        brand: "VisiNest",
        material: "Wood",
        color: "Brown",
        weight: "Light",
        stock: 15,
        shortDescription: "Compact single-seat sofa made of wood.",
        detailDescription: "Perfect for small spaces, the Cozy Nook Single Seat offers comfort and durability in a compact design. The brown wooden frame provides a sturdy base, while the cushioned seat ensures comfort. Ideal for living rooms or cozy reading nooks."
    },
    {
        id: 6,
        name: "Vintage Grace Dressing Table",
        imageUrl: "/Product_img/products6.png",
        rating: 4.8,
        price: 69.99,
        reviews: 500,
        type: "Table",
        brand: "VisiARrange",
        material: "Wood",
        color: "Brown",
        weight: "Heavy",
        stock: 4,
        shortDescription: "Elegant antique-style wooden dressing table.",
        detailDescription: "The Vintage Grace Dressing Table brings a touch of vintage charm to your bedroom. Featuring a spacious tabletop and intricate wood detailing, it offers both functionality and timeless beauty. Ideal for organizing personal items and accessories."
    },
    {
        id: 7,
        name: "Timeless Vanity Station",
        imageUrl: "/Product_img/products7.png",
        rating: 3.9,
        price: 22.99,
        reviews: 85,
        type: "Table",
        brand: "VisiFurnish",
        material: "Wood",
        color: "Brown",
        weight: "Light",
        stock: 10,
        shortDescription: "Chic and functional vanity table for daily use.",
        detailDescription: "The Timeless Vanity Station is perfect for makeup and grooming routines. Its compact size fits well in smaller spaces, while the wooden design adds a warm, natural touch. Features ample storage space for beauty essentials."
    },
    {
        id: 8,
        name: "Shadow Stow Cupboard",
        imageUrl: "/Product_img/products8.png",
        rating: 4.3,
        price: 33.99,
        reviews: 205,
        type: "Storage",
        brand: "VisiNest",
        material: "Wood",
        color: "Brown",
        weight: "Medium",
        stock: 6,
        shortDescription: "Sturdy black wooden cupboard for extra storage.",
        detailDescription: "The Shadow Stow Cupboard provides ample storage space with a sturdy wooden build. Finished in sleek black, this medium-weight cupboard is ideal for bedrooms, living rooms, or offices, helping you stay organized while enhancing your decor."
    },
    {
        id: 9,
        name: "Abstract Horizon Canvas",
        imageUrl: "/Product_img/products9.png",
        rating: 4.7,
        price: 55.99,
        reviews: 315,
        type: "Decor",
        brand: "VisiARrange",
        material: "Canvas",
        color: "Silver",
        weight: "Light",
        stock: 20,
        shortDescription: "Contemporary abstract art on canvas for modern interiors.",
        detailDescription: "The Abstract Horizon Canvas piece is perfect for adding a modern and artistic touch to your living space. The subtle gray tones blend well with a variety of color schemes, making it a versatile decor item for any room in your home."
    },
    {
        id: 10,
        name: "Ivory Cloud White Sofa",
        imageUrl: "/Product_img/products10.png",
        rating: 5.0,
        price: 89.99,
        reviews: 400,
        type: "Sofa",
        brand: "VisiFurnish",
        material: "Fabric",
        color: "White",
        weight: "Heavy",
        stock: 3,
        shortDescription: "Spacious white fabric sofa for ultimate comfort.",
        detailDescription: "Sink into the plush cushions of the Ivory Cloud Sofa, designed with high-quality fabric and a sturdy frame. The neutral gray color makes it an easy fit for any home decor, while the heavy build ensures long-lasting durability."
    },
    {
        id: 11,
        name: "Sunshine Accent Brown Sofa",
        imageUrl: "/Product_img/products11.png",
        rating: 4.1,
        price: 23.99,
        reviews: 160,
        type: "Sofa",
        brand: "VisiNest",
        material: "Fabric",
        color: "Brown",
        weight: "Medium",
        stock: 8,
        shortDescription: "Stylish yellow accent sofa for a pop of color.",
        detailDescription: "Add a bold touch to your living room with the Sunshine Accent Sofa. Its medium-weight design makes it easy to move, while the vibrant color and soft fabric make it a comfortable and eye-catching addition to any space."
    },
    {
        id: 12,
        name: "Jetstream ",
        imageUrl: "/Product_img/products12.png",
        rating: 4.6,
        price: 42.99,
        reviews: 280,
        type: "",
        brand: "VisiARrange",
        material: "Plastic",
        color: "Black",
        weight: "Light",
        stock: 12,
        shortDescription: "Sleek and durable plastic chair for modern interiors.",
        detailDescription: "The Jetstream Chair offers a minimalist and durable seating option for both indoor and outdoor spaces. Its black color and lightweight design make it versatile for any environment, providing comfort and style without compromising on durability."
    },
 {
    id: 81,
    name: 'Samsung Galaxy',
    imageUrl: '/Product_img/watch-01.png',
    price: 199,
    rating: 4.5,
    brand: 'Samsung',
    type: 'Watches',
    material: 'Metal',
    color: 'Black',
    weight: 'Light',
    stock: 10,
    shortDescription: 'A stylish and sleek metal-bodied smartwatch by Samsung, perfect for fitness tracking and notifications.',
    detailDescription: 'The Samsung Galaxy Watch 4 combines premium design with functionality, offering health monitoring, fitness tracking, and seamless notifications. With its durable metal body and vibrant display, it’s perfect for both casual and active lifestyles.'
  },
  {
    id: 82,
    name: 'Fossil Hybrid HR',
    imageUrl: '/Product_img/watch-02.jpg',
    price: 249,
    rating: 4.2,
    brand: 'Fossil',
    type: 'Watches',
    material: 'Leather',
    color: 'Silver',
    weight: 'Medium',
    stock: 5,
    shortDescription: 'A classic hybrid watch by Fossil, combining vintage looks with modern technology.',
    detailDescription: 'The Fossil Hybrid HR blends traditional aesthetics with modern smartwatch features. It includes long battery life, and all while maintaining the elegance of a belt-strap watch.'
  },
  {
    id: 83,
    name: 'Garmin Fenix 6X',
    imageUrl: '/Product_img/watch-03.jpg',
    price: 299,
    rating: 4.7,
    brand: 'Garmin',
    type: 'Watches',
    material: 'Metal',
    color: 'Silver',
    weight: 'Light',
    stock: 8,
    shortDescription: 'A high-performance multisport watch from Garmin',
    detailDescription: 'Garmin Fenix is designed for athletes and adventurers, and multiple sport modes. Its rugged metal body and versatile functionality make it ideal for outdoor enthusiasts.'
  },
  {
    id: 84,
    name: 'Tag Heuer Connected',
    imageUrl: '/Product_img/watch-04.jpg',
    price: 399,
    rating: 4.9,
    brand: 'Tag Heuer',
    type: 'Watches',
    material: 'Leather',
    color: 'Black',
    weight: 'Medium',
    stock: 7,
    shortDescription: 'A luxury smartwatch from Tag Heuer, blending premium design with cutting-edge technology.',
    detailDescription: 'The Tag Heuer Connected offers the perfect blend of luxury and technology. With a premium leather strap and advanced fitness tracking, it is designed for individuals who appreciate elegance and performance.'
  },
  {
    id: 91,
    name: 'Xiaomi Redmi Note 13',
    imageUrl: '/Product_img/phone1.jpg',
    price: 799,
    rating: 4.8,
    brand: 'Xiaomi',
    type: 'Mobiles',
    material: 'Metal',
    color: 'White',
    weight: 'Heavy',
    stock: 15,
    shortDescription: 'A powerful Xiaomi smartphone designed for mobile gaming and high performance.',
    detailDescription: 'The Xiaomi Redmi Note 13 features a sleek metal design and a high-refresh-rate display, making it ideal for gaming and multitasking. Its powerful chipset ensures smooth performance, while its long-lasting battery is perfect for heavy users.'
  },
  {
    id: 92,
    name: 'Samsung Galaxy F23',
    imageUrl: '/Product_img/phone2.jpg',
    price: 899,
    rating: 4.5,
    brand: 'Samsung',
    type: 'Mobiles',
    material: 'Plastic',
    color: 'Silver',
    weight: 'Medium',
    stock: 7,
    shortDescription: 'An affordable Samsung smartphone offering fast performance and a great camera.',
    detailDescription: 'The Samsung Galaxy F23 provides excellent performance with its efficient chipset and long-lasting battery. With a sturdy plastic body and an impressive camera, it’s a great choice for users who want value without compromising on features.'
  },
  {
    id: 93,
    name: 'Realme 8 Pro',
    imageUrl: '/Product_img/phone3.jpg',
    price: 999,
    rating: 4.9,
    brand: 'Oppo',
    type: 'Mobiles',
    material: 'Plastic',
    color: 'Gray',
    weight: 'Medium',
    stock: 12,
    shortDescription: 'A sleek Realme smartphone offering cutting-edge technology with a striking blue finish.',
    detailDescription: 'The Realme 8 Pro combines fast performance with a stunning design. Its blue plastic body is both durable and lightweight, and its advanced camera system makes it perfect for photography enthusiasts.'
  },
  {
    id: 94,
    name: 'Motorola Edge 40 Neo',
    imageUrl: '/Product_img/phone4.jpg',
    price: 1099,
    rating: 4.6,
    brand: 'Motorola',
    type: 'Mobiles',
    material: 'Glass',
    color: 'Silver',
    weight: 'Heavy',
    stock: 10,
    shortDescription: 'A premium Motorola smartphone with a glass back, offering a great camera and battery life.',
    detailDescription: 'The Motorola Edge 40 Neo is designed for those who prioritize aesthetics and performance. With a premium glass body and a powerful camera system, it’s ideal for users who want a high-end smartphone experience.'
  },
  {
    id: 95,
    name: 'iPhone 13',
    imageUrl: '/Product_img/phone5.jpg',
    price: 1599,
    rating: 4.8,
    brand: 'Apple',
    type: 'Mobiles',
    material: 'Glass',
    color: 'Silver',
    weight: 'Heavy',
    stock: 10,
    shortDescription: 'The latest iPhone with cutting-edge technology and a sleek glass body.',
    detailDescription: 'The iPhone 13 offers unparalleled performance with its A15 Bionic chip, stunning display, and excellent camera system. Its glass back adds a premium feel, making it a top choice for iPhone fans.'
  },
  {
    id: 71,
    name: 'Dell Inspiron 15',
    imageUrl: '/Product_img/laptop1.jpg',
    price: 1199,
    rating: 4.7,
    brand: 'Dell',
    type: 'Laptops',
    material: 'Aluminum',
    color: 'Gray',
    weight: 'Heavy',
    stock: 8,
    shortDescription: 'A high-performance Dell laptop designed for both professionals and students.',
    detailDescription: 'The Dell Inspiron 15 combines powerful performance with a sleek aluminum design. Its large display and excellent battery life make it perfect for professionals and students alike.'
  },
  {
    id: 72,
    name: 'HP 15s',
    imageUrl: '/Product_img/laptop2.jpg',
    price: 1299,
    rating: 4.6,
    brand: 'HP',
    type: 'Laptops',
    material: 'Plastic',
    color: 'Gray',
    weight: 'Heavy',
    stock: 10,
    shortDescription: 'An affordable HP laptop offering good performance and a long battery life.',
    detailDescription: 'The HP 15s is designed for users who need a reliable laptop for everyday tasks. Its plastic body is durable, and its battery life is excellent, making it a solid choice for students and home users.'
  },
  {
    id: 73,
    name: 'Lenovo IdeaPad 5',
    imageUrl: '/Product_img/laptop3.jpg',
    price: 1399,
    rating: 4.8,
    brand: 'Lenovo',
    type: 'Laptops',
    material: 'Aluminum',
    color: 'Silver',
    weight: 'Medium',
    stock: 6,
    shortDescription: 'A lightweight Lenovo laptop with a sleek aluminum design and good performance.',
    detailDescription: 'The Lenovo IdeaPad 5 is perfect for both work and play, featuring a lightweight aluminum body and powerful specs. Its vibrant display and excellent battery life make it a great choice for anyone looking for a portable laptop.'
  },
  {
    id: 74,
    name: 'Lenovo Think Pad',
    imageUrl: '/Product_img/laptop4.jpg',
    price: 1499,
    rating: 4.8,
    brand: 'Lenovo',
    type: 'Laptops',
    material: 'Aluminum',
    color: 'Black',
    weight: 'Medium',
    stock: 6,
    shortDescription: 'A lightweight Lenovo laptop with a sleek aluminum design and good performance.',
    detailDescription: 'The Lenovo Think Pad is perfect for both work and play, featuring a lightweight aluminum body and powerful specs. Its vibrant display and excellent battery life make it a great choice for anyone looking for a portable laptop.'
  },
  {
    id: 75,
    name: 'HP Pavillion',
    imageUrl: '/Product_img/laptop5.jpg',
    price: 1699,
    rating: 4.7,
    brand: 'Hp',
    type: 'Laptops',
    material: 'Plastic',
    color: 'Silver',
    weight: 'Medium',
    stock: 4,
    shortDescription: 'Hp Pavallion laptop offering cutting-edge technology, lightweight design, and fast performance for multitaskers.',
    detailDescription: 'Hp Pavallion offers the latest technology in a sleek and lightweight body. Its fast processing power is ideal for multitasking, while its plastic construction ensures durability without adding extra weight. A great option for both professionals and students.'
  }
];
 
export default products;